server.port=8080

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Routes mapping
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admin/users/**, /api/admin/audit-logs/**

spring.cloud.gateway.routes[2].id=borrower-service
spring.cloud.gateway.routes[2].uri=lb://borrower-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/borrowers/**, /api/kyc/**

spring.cloud.gateway.routes[3].id=group-service
spring.cloud.gateway.routes[3].uri=lb://group-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/centres/**, /api/groups/**, /api/meetings/**

spring.cloud.gateway.routes[4].id=loan-service
spring.cloud.gateway.routes[4].uri=lb://loan-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/loan-products/**, /api/loan-applications/**, /api/credit-assessments/**, /api/sanction-letters/**, /api/loan-accounts/**

spring.cloud.gateway.routes[5].id=emi-service
spring.cloud.gateway.routes[5].uri=lb://emi-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/collections/**, /api/delinquency/**

spring.cloud.gateway.routes[6].id=notification-service
spring.cloud.gateway.routes[6].uri=lb://notification-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[7].id=report-service
spring.cloud.gateway.routes[7].uri=lb://report-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/reports/**
